language: cpp
compiler: clang

before_install:
    - sudo apt-get -y install lcov

script:
    - python3 misc/test_zlib_debug_compressor.py
    - mkdir -p build
    - cd build
    - clang -lm -O2 ../misc/fuzz_deflate.c -o fuzz_deflate
    - clang -lm -O2 ../misc/test_deflate.c -o test_deflate
    - clang++ -lm ../misc/test_build.cpp -o test_build_cpp
    - python3 ../misc/test_deflate.py ./test_deflate ..
    - clang -lm -O2 -std=gnu99 -Wno-unused-value -D_GNU_SOURCE ../ufbx.c ../test/runner.c -o runner
    - ./runner -d ../data
    - clang -lm -g -std=gnu99 -Wno-unused-value -D_GNU_SOURCE -DUFBX_NO_UNALIGNED_LOADS ../ufbx.c ../test/runner.c -o runner
    - ./runner -d ../data
    - clang -lm -coverage -g -std=gnu99 -Wno-unused-value -D_GNU_SOURCE ../ufbx.c ../test/runner.c -o runner
    - catchsegv ./runner -v -d ../data/
    - llvm-cov gcov ufbx runner -b
    - printf '#!/bin/bash\nexec llvm-cov gcov "$@"\n' > llvm-gcov.sh
    - chmod +x llvm-gcov.sh
    - lcov --directory . --base-directory . --gcov-tool ./llvm-gcov.sh --rc lcov_branch_coverage=1 --capture -o coverage.lcov

after_success:
    - bash <(curl -s https://codecov.io/bash) -f coverage.lcov -y misc/codecov.yml
